# Generated by Django 3.2.3 on 2021-06-13 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_diagnosis_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='time',
            field=models.CharField(blank=True, default='June 12, 2021', max_length=64, null=True),
        ),
    ]
