# Generated by Django 3.2.3 on 2021-06-13 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_diagnosis_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='location',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
